import pandas as pd
d= pd.read_csv(r"D:\Code\Python\CSV\india_population.csv")
print(d)
#print(d.head(4))
#print(d.tail(5))
#print(d.info())
#print(d["Age"].describe())
#print(d.columns)
#print(d.shape)
#print(d.dtypes)
#print(d.index)
#print(d["World Population"].value_counts())
#print(d["Year"].unique())
#print(d["Urban Population"].mean())
#print(d["Urban Population"].median())
#print(d[["Year", "Urban Population"]])
#print(d.loc[2:5])
#print(d.iloc[0:5,0:3])
#print(d.iloc[2])
#print(d["Fertility Rate"])
#print(d[["Year", "Fertility Rate"]])
#print(d["Density"])     #Density P/KmÂ²
