import pandas as pd
d= pd.read_csv(r"D:\Code\Python\CSV\diabetes.csv")
#print(d)
#print(d.head(4))
#print(d.tail(5))
#print(d.info())
#print(d["Age"].describe())
#print(d.columns)
#print(d.shape)
#print(d.dtypes)
#print(d.index)
#print(d["Outcome"].value_counts())
#print(d["Outcome"].unique())
#print(d["Age"].unique())
#print(d["Age"].mean())
#print(d["Age"].median())
#print(d[["Age", "Outcome"]])
#print(d.loc[2:5])
print(d.iloc[0:5,0:3])
#print(d.iloc[2])
#print(d["Age"])